### ISSUE TITLE
Architectural overview

### ISSUE THREAD

**Issue by maxdeviant** [merveilles/Rotonde#1]
Here is a brief overview of the planned Rotonde architecture:

## Packages

All core Rotonde work will be done in this repo, but functionality will be broken up into individual packages that can be consumed by `rotonde-core`. We will also be able to consume third-party packages from other sources, but anything considered a tier 1 package should live in this repository.

There are a few different types of packages, denoted by their naming conventions:

- **rotonde-*** - These packages will make up the core infrastructure of Rotonde.
- **rotonde-plugin-*** - These packages will be the plugins that support the core functionality of Rotonde.
- **rotonde-deploy-*** - These packages will provide the ability to deploy a Rotonde instance to various hosting providers.
- **rotonde-util-*** - These packages will contain utilities for Rotonde that can be shared between any of the packages.

This list of packages will be adjusted on an as-needed basis, should we find some new category of package that is required.

### rotonde-core

The Rotonde core is a web server built on top of Express and Socket.IO. The core itself should be fairly light, and will really just be for orchestrating all of the different plugins.

### rotonde-registry

The Rotonde registry maintains an active list of Rotonde instances, and will be hosted permanently at some location. Whenever a new Rotonde instance is started, it will try to register itself with the main registry so that it can discover other instances, and those instances can also discover it.

### rotonde-cli

The Rotonde CLI provides command line access to the Rotonde core. Install it with `npm i -g rotonde-cli`!

### rotonde-plugin-chat

The Rotonde chat plugin provides the ability to chat with other users. The plugin should support chat between users on the current Rotonde instance, as well as using that instance as a portal to connect to another Rotonde instance and being able to chat there.

### rotonde-plugin-ui

The Rotonde UI plugin provides the primary user interface that we will design for using Rotonde. It will be able to be customized or replaced entirely with other plugins, but this will be the one that ships as the default with Rotonde.

### rotonde-deploy-server

The Rotonde deploy server plugin provides the ability to deploy a Rotonde instance to any Linux server as a Node process. It will run on a local port, and it is up to the server administrator to configure their web server (e.g., nginx, Apache, etc.) to forward the traffic to Rotonde.

### rotonde-deploy-local

The Rotonde deploy local plugin provides the ability to run a Rotonde instance on a local system. This is something that will need to be investigated in the future for viability.

### rotonde-deploy-now

The Rotonde deploy now plugin provides the ability to deploy a Rotonde instance to [now](https://zeit.co/now/).

### rotonde-deploy-*

There will be any other number of deploy plugins available for deploying Rotonde instances to various hosts, such as AWS, Google Cloud, Heroku, etc.

**Comment by y4my4my4m** [comment]
y4my4m here

@maxdeviant and I discussed that we could use **React** and **[Glamor](https://github.com/threepointone/glamor)** for the front-end.

**Comment by ESWAT** [comment]
What have we settled on for the JS abstraction we’ll write in? I know TypeScript was mentioned in chat a few times and `rotonde-core` has ES6. For the record I think we should just stick with ES6 as it’s one less extra hurdle for someone that wants to contribute.
